# global parameters
project_name: 'Data-Juicer-recipes-alpaca-cot-en'
dataset_path: '../data/raw_data/raw_data_en.jsonl'  # path to your dataset directory or file
export_path: ''
ds_cache_dir: '~/data1/huggingface/datasets'

np: 100  # number of subprocess to process your dataset
open_tracer: true
trace_num: 100

# process schedule
# a list of several process operators with their arguments
process:

# for instruction mapper
  - fix_unicode_mapper:
      text_key: 'instruction'
  - whitespace_normalization_mapper:
      text_key: 'instruction'
  - chinese_convert_mapper:
      text_key: 'instruction'
      mode: t2s

  # for output mapper
  - fix_unicode_mapper:
      text_key: 'output'
  - whitespace_normalization_mapper:
      text_key: 'output'
  - chinese_convert_mapper:
      text_key: 'output'
      mode: t2s
