# global parameters
project_name: 'Data-Juicer-recipes-alpaca-cot-en'
dataset_path: '../data/raw_data/raw_data_en.jsonl'  # path to your dataset directory or file
export_path: '../data/html_try_data_en/dataset.jsonl'
ds_cache_dir: '~/data1/huggingface/datasets'

np: 100  # number of subprocess to process your dataset
open_tracer: true
trace_num: 50

# process schedule
# a list of several process operators with their arguments
process:
  - clean_html_mapper:
