# global parameters
project_name: 'Data-Juicer-recipes-alpaca-cot-zh'
dataset_path: '../data/raw_data/raw_data_zh.jsonl'  # path to your dataset directory or file
export_path: '../data/refine_data_zh/dataset_zh.jsonl'
ds_cache_dir: '~/data1/huggingface/datasets'

np: 100  # number of subprocess to process your dataset
open_tracer: true
trace_num: 50

# process schedule
# a list of several process operators with their arguments
process:
  - document_deduplicator: # 16957516
      lowercase: true # whether to convert text to lower case
      ignore_non_character: true

  - alphanumeric_filter: # 16957388
      tokenization: false
      min_ratio: 0.10  
  - character_repetition_filter: # 16956845
      rep_len: 10
      max_ratio: 0.6  
  - flagged_words_filter: # 16954629
      lang: zh
      tokenization: true
      use_words_aug: true
      max_ratio: 0.017
  - text_length_filter: # 16954317
      min_len: 10
  - perplexity_filter:                                      # filter text with perplexity score out of specific range
      lang: zh                                                # compute perplexity in what language
      max_ppl: 1000
  - language_id_score_filter:                               # filter text in specific language with language scores larger than a specific max value
      lang: zh                                                # keep text in what language
      min_score: 0.8

  - document_simhash_deduplicator: # 9873214
      tokenization: character
      window_size: 4  # small window size for short texts
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 10
      hamming_distance: 8  # larger hamming distance threshold for short texts
