# Process config example for dataset

# global parameters
project_name: 'demo-dedup'
dataset_path: './demos/data/demo-dataset-deduplication.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

open_tracer: true

export_path: './outputs/demo-dedup/demo-dedup-processed.jsonl'

# process schedule
# a list of several process operators with their arguments
process:
  - language_id_score_filter:
      lang: en
      min_score: 0.5
#  - document_deduplicator:
#      lowercase: false
#      ignore_non_character: false
  - document_minhash_deduplicator:
      tokenization: 'character'
