# global parameters
project_name: 'Data-Juicer-recipes-Hin'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
export_path: '/path/to/your/dataset.jsonl'

np: 50  # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments
process:
  - clean_email_mapper:
  - clean_links_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:

  - alphanumeric_filter:
      tokenization: false
      min_ratio: 0.75  # <3sigma (0.800)
      max_ratio: 0.866
  - average_line_length_filter:
      max_len: 10000  # >3sigma (5425)
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.2  # >3sigma (0.127)
  - flagged_words_filter:
      lang: en
      tokenization: true
      max_ratio: 0.0003  # 3sigma
  - language_id_score_filter:
      min_score: 0.7
  - perplexity_filter:
      lang: en
      max_ppl: 1669 #(3sigma)
  - special_characters_filter:
      max_ratio: 0.3  # > 3sigma (0.218)
  - words_num_filter:
      tokenization: true
      min_num: 20
      max_num: 2000
  - word_repetition_filter:
      lang: en
      tokenization: true
      rep_len: 10
      max_ratio: 0.104  # 3sigma

  - document_simhash_deduplicator:
      tokenization: space
      window_size: 6
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 6
      hamming_distance: 4
