# global parameters
project_name: 'Data-Juicer-recipes-pubmed-central'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
export_path: '/path/to/your/dataset.jsonl'

np: 50  # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments
process:
  - clean_email_mapper:
  - clean_links_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:

  - alphanumeric_filter:  # 89217
      tokenization: false
      min_ratio: 0.2787  # 3sigma
  - average_line_length_filter:  # for code
      max_len: 1200  # < 3sigma (1478) -- 7410
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.3741  # 3sigma -- 65849
  - flagged_words_filter:
      lang: en
      tokenization: true
      max_ratio: 0.00195  # 3sigma -- 8305
  - language_id_score_filter:  # remove language filter
      min_score: 0.5  # 272359
  - maximum_line_length_filter:  # for code
      max_len: 7328  # remove 23808 samples
  - perplexity_filter:
      lang: en
      max_ppl: 8000  # remove 173883 samples
  - special_characters_filter:
      max_ratio: 0.842  # remove 87661 samples
  - text_length_filter:
      max_len: 136028  # 3sigma -- 15118
  - words_num_filter:
      lang: en
      tokenization: true
      min_num: 20  # remove 176537 samples
      max_num: 23305  # remove 15016 samples
  - word_repetition_filter:
      lang: en
      tokenization: true
      rep_len: 10
      max_ratio: 0.5981  # 3sigma -- 93843

  - document_simhash_deduplicator:
      tokenization: space
      window_size: 6
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 6
      hamming_distance: 4
