# global parameters
project_name: 'Data-Juicer-recipes-freelaw'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
export_path: '/path/to/your/dataset.jsonl'

np: 50  # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments
process:
  - clean_email_mapper:
  - clean_links_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:

  - alphanumeric_filter:
      tokenization: false
      min_ratio: 0.3  # <3sigma (0.436)
  - average_line_length_filter:  # for code
      max_len: 697  # 3sigma TBD
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.4  # >3sigma (0.350)
  - flagged_words_filter:
      lang: en
      tokenization: true
      max_ratio: 0.0053  # 3sigma
  - language_id_score_filter:
      min_score: 0.5 # < 3sigma (0.583)
  - maximum_line_length_filter:  # for code
      max_len: 4229  # 3sigma
  - perplexity_filter:
      lang: en
      max_ppl: 5322  # 3sigma
  - special_characters_filter:
      max_ratio: 0.7  # > 3sigma (0.626)
  - stopwords_filter:  # not use
      lang: en
      tokenization: true
      min_ratio: 0.1 # > 3sigma (0.07)
  - text_length_filter:
      max_len: 84026 # 3sigma
  - words_num_filter:
      lang: en
      tokenization: true
      min_num: 100
      max_num: 15208  # 3sigma
  - word_repetition_filter:
      lang: en
      tokenization: true
      rep_len: 10
      max_ratio: 0.155  # 3sigma

  - document_simhash_deduplicator:
      tokenization: space
      window_size: 6
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 6
      hamming_distance: 4
