# global parameters
project_name: 'Data-Juicer-recipes-cc-2020-05'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
export_path: '/path/to/your/dataset.jsonl'

np: 50  # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments
process:
  - document_simhash_deduplicator:
      tokenization: space
      window_size: 6
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 6
      hamming_distance: 4

  - clean_email_mapper:
  - clean_links_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:

  - alphanumeric_filter:
      tokenization: false
      min_ratio: 0.7469  # 3sigma
      max_ratio: 0.8609  # 3sigma
  - average_line_length_filter:  # for code
      max_len: 1500  # < 3sigma -- 332621
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.3  # > 3sigma -- 170501
  - flagged_words_filter:
      lang: en
      tokenization: true
      max_ratio: 0.002  # 3sigma -- 167167
  - language_id_score_filter:  # remove language filter
      min_score: 0.774  # 3sigma -- 1943513
  - maximum_line_length_filter:  # for code
      max_len: 5000  # < 3sigma -- 845490
  - perplexity_filter:
      lang: en
      max_ppl: 5000  # < 3sigma -- 909218
  - special_characters_filter:
      min_ratio: 0.15  # > 3sigma
      max_ratio: 0.35  # > 3sigma -- 1134347
  - text_length_filter:
      max_len: 68161  # 3sigma -- 1145902
  - words_num_filter:
      lang: en
      tokenization: true
      min_num: 20  # remove 7913 samples
      max_num: 13644  # 3sigma -- 1148810
  - word_repetition_filter:
      lang: en
      tokenization: true
      rep_len: 10
      max_ratio: 0.328  # 3sigma -- 2125070
