# global parameters
project_name: 'Data-Juicer-arxivrecipes-arxiv'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
export_path: '/path/to/your/dataset.jsonl'

np: 50  # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments
process:
  - clean_email_mapper:
  - clean_links_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:

  - alphanumeric_filter:
      tokenization: false
      min_ratio: 0.516  # 3sigma
      max_ratio: 0.915  # 3sigma
  - average_line_length_filter:  # for code
      max_len: 682  # 3sigma
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.3
  - flagged_words_filter:
      lang: en
      tokenization: true
      max_ratio: 0.00076  # 3sigma
  #- language_id_score_filter:  # remove language filter
  - maximum_line_length_filter:  # for code
      max_len: 4000
  - perplexity_filter:
      lang: en
      max_ppl: 8000
  - special_characters_filter:
      max_ratio: 0.6
  - text_length_filter:
      max_len: 350000
  - words_num_filter:
      lang: en
      tokenization: true
      min_num: 20
      max_num: 100000
  - word_repetition_filter:
      lang: en
      tokenization: true
      rep_len: 10
      max_ratio: 0.574  # 3sigma

  - document_simhash_deduplicator:
      tokenization: space
      window_size: 6
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 6
      hamming_distance: 4
