# global parameters
project_name: 'Data-Juicer-recipes-cc-2013-06'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
export_path: '/path/to/your/dataset.jsonl'

np: 50  # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments
process:
  - document_simhash_deduplicator:
      tokenization: space
      window_size: 6
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 6
      hamming_distance: 4

  - clean_email_mapper:
  - clean_links_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:

  - alphanumeric_filter:
      tokenization: false
      min_ratio: 0.7508  # 3sigma
      max_ratio: 0.8591  # 3sigma -- 1036821
  - average_line_length_filter:  # for code
      max_len: 1500  # < 3sigma -- 395868
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.3  # > 3sigma -- 195026
  - flagged_words_filter:
      lang: en
      tokenization: true
      max_ratio: 0.0015  # 3sigma -- 287896
  - language_id_score_filter:  # remove language filter
      min_score: 0.793  # 3sigma -- 2173246
  - maximum_line_length_filter:  # for code
      max_len: 5000  # < 3sigma -- 797111
  - perplexity_filter:
      lang: en
      max_ppl: 5000  # 3sigma -- 942162
  - special_characters_filter:
      min_ratio: 0.15  # > 3sigma
      max_ratio: 0.35  # > 3sigma -- 1155090
  - text_length_filter:
      max_len: 58187  # 3sigma -- 1165902
  - words_num_filter:
      lang: en
      tokenization: true
      min_num: 20
      max_num: 11529  # 3sigma -- 1185363
  - word_repetition_filter:
      lang: en
      tokenization: true
      rep_len: 10
      max_ratio: 0.2962  # 3sigma -- 2407282
