# global parameters
project_name: 'Exp-Max-Line-Length'
dataset_path: 'data/raw_data/raw_data_en.jsonl'  # path to your dataset directory or file
export_path: ''
ds_cache_dir: '~/data3/huggingface/datasets'

np: 100  # number of subprocess to process your dataset
open_tracer: true
trace_num: 100

# process schedule
# a list of several process operators with their arguments
process:
  - maximum_line_length_filter: # 104575811
      min_len: 10
      max_len: 10000