# Process config example for stackexchange used in RedPajam

# global parameters
project_name: 'RedPajam-stackexchange'
dataset_path: '/path/to/your/dataset'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset
use_cache: False

export_path: '/path/to/result/dataset.jsonl'

# process schedule
# a list of several process operators with their arguments
process:
  - clean_html_mapper:
  - language_id_score_filter:
      lang: ''
      min_score: 0.0
